@startuml
interface TaskComponent {
    +add(TaskComponent task)
    +remove(TaskComponent task)
    +get_child(int index)
    +get_name(): string
}

class Task {
    -name: string
    +__init__(name: string)
    +add(TaskComponent task)
    +remove(TaskComponent task)
    +get_child(int index)
    +get_name(): string
}

class Project {
    -name: string
    -tasks: TaskComponent[]
    +__init__(name: string)
    +add(TaskComponent task)
    +remove(TaskComponent task)
    +get_child(int index)
    +get_name(): string
}

TaskComponent <|-- Task
TaskComponent <|-- Project
@enduml