@startuml
interface DataSourceInterface {
    +getData(): array
}

class NalogRuDataSource {
    +fetchData(): array
}

class DadataRuDataSource {
    +retrieveData(): array
}

class NalogRuAdapter {
    -nalogRuDataSource: NalogRuDataSource
    +__construct(NalogRuDataSource)
    +getData(): array
}

class DadataRuAdapter {
    -dadataRuDataSource: DadataRuDataSource
    +__construct(DadataRuDataSource)
    +getData(): array
}

DataSourceInterface <|.. NalogRuAdapter
DataSourceInterface <|.. DadataRuAdapter

NalogRuAdapter --> NalogRuDataSource
DadataRuAdapter --> DadataRuDataSource
@enduml