@startuml
interface DataSourceInterface {
    +GetData(): map[string]string
}

class NalogRuDataSource {
    +FetchData(): map[string]interface{}
}

class DadataRuDataSource {
    +RetrieveData(): map[string]interface{}
}

class NalogRuAdapter {
    -DataSource: NalogRuDataSource
    +GetData(): map[string]string
}

class DadataRuAdapter {
    -DataSource: DadataRuDataSource
    +GetData(): map[string]string
}

DataSourceInterface <|.. NalogRuAdapter
DataSourceInterface <|.. DadataRuAdapter

NalogRuAdapter --> NalogRuDataSource
DadataRuAdapter --> DadataRuDataSource
@enduml