@startuml

abstract class Template {
    + clone(): Template
}

class PageTemplate {
    - title: str
    - content: str
    - args: tuple
    - kwargs: dict
    + __init__(title: str, content: str, *args, **kwargs): PageTemplate
    + clone(): PageTemplate
}

class Page {
    - title: str
    - content: str
    - args: tuple
    - kwargs: dict
    + __init__(title: str, content: str, *args, **kwargs): Page
}

class PageFactory {
    - prototypes: dict
    + __init__(): PageFactory
    + create_page(template_name: str, title: str, content: str, *args, **kwargs): Page
}

Template <|-- PageTemplate
PageFactory o-- PageTemplate
PageFactory --> Page

@enduml
