@startuml

interface Observable {
    +attach(Observer observer)
    +detach(Observer observer)
    +notify()
}

interface Observer {
    +update(Observable observable)
}

class Server {
    -status: string
    -observers: Observer[]
    +attach(Observer observer)
    +detach(Observer observer)
    +notify()
    +changeStatus(newStatus: string)
    +getStatus(): string
}

class Admin {
    -name: string
    +__construct(name: string)
    +update(Observable observable)
}

Observable <|-- Server
Observer <|-- Admin

@enduml