@startuml

class Mediator {
    +send(message: string, colleague: Colleague): void
}

abstract class Colleague {
    -mediator: Mediator
    +setMediator(mediator: Mediator): void
    +send(message: string): void
    +receive(message: string): void
}

class ConcreteColleague1 {
    +send(message: string): void
    +receive(message: string): void
}

class ConcreteColleague2 {
    +send(message: string): void
    +receive(message: string): void
}

Mediator <|-- ConcreteColleague1
Mediator <|-- ConcreteColleague2
Colleague <|-- ConcreteColleague1
Colleague <|-- ConcreteColleague2

@enduml