@startuml
interface DataSourceInterface {
    +getData(): array
}

class YandexMetrikaDataSource {
    +fetchData(): array
}

class RoistatDataSource {
    +retrieveData(): array
}

class Bitrix24DataSource {
    +getBitrixData(): array
}

class YandexMetrikaAdapter {
    -yandexMetrikaDataSource: YandexMetrikaDataSource
    +__construct(YandexMetrikaDataSource)
    +getData(): array
}

class RoistatAdapter {
    -roistatDataSource: RoistatDataSource
    +__construct(RoistatDataSource)
    +getData(): array
}

class Bitrix24Adapter {
    -bitrix24DataSource: Bitrix24DataSource
    +__construct(Bitrix24DataSource)
    +getData(): array
}

DataSourceInterface <|.. YandexMetrikaAdapter
DataSourceInterface <|.. RoistatAdapter
DataSourceInterface <|.. Bitrix24Adapter

YandexMetrikaAdapter --> YandexMetrikaDataSource
RoistatAdapter --> RoistatDataSource
Bitrix24Adapter --> Bitrix24DataSource
@enduml